# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = "$username$hostname$battery$all$character"
right_format = "$time"

[aws]
disabled = true

[time]
style = "244"
format = "âˆ™[$time]($style)âˆ™"
disabled = false

[username]
format = "[$user]($style)"
show_always = true
disabled = false

[hostname]
style = "244"
format = "/[$ssh_symbol$hostname]($style)"
ssh_only = false
disabled = false

[battery]
format = " ï˜½ [$symbol$percentage]($style)"
disabled = false

[[battery.display]]
threshold = 90
style = "bold red"

[directory]
format = ' ï˜½ [$path]($style)[$read_only]($read_only_style)'

[git_branch]
format = " ï˜½ ï˜ [$branch(:$remote_branch)]($style) "

[git_commit]
style = "244"
format = '\([$hash$tag]($style)\) '
only_detached = false

[git_status]
format = ': \([$all_status$ahead_behind]($style) \)'
conflicted = " = [$count](244)" #This branch has merge conflicts.
ahead = " â‡¡ [$count](244)" #The format of ahead
behind = " [â‡£]()" #The format of behind
diverged = " [â‡•]()" #The format of diverged
up_to_date = "" #The format of up_to_date
untracked = " ? [$count](244)" #The format of untracked
stashed = " ğŸ“¦ [$count](244)" #The format of stashed
modified = " ï€ [$count](244)" #The format of modified
staged = " ï°™ [$count](244)" #The format of staged
renamed = " Â» [$count](244)" #The format of renamed
deleted	= " âœ˜ [$count](244)"

[package]
symbol = 'ğŸ“¦'
format = " ï˜½ [$symbol]($style)/[$version](244)"
disabled = false

[nodejs]
symbol = "node"
format = " ï˜½ [$symbol]($style)/[$version](244)"

[rust]
symbol = "rust"
format = " ï˜½ [$symbol]($style)/[$version](244)"

[cmd_duration]
min_time = 500
show_milliseconds = false
format = " ï˜½ [ï¨š$duration]($style) "

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ï²¤](bold green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[ï²¤](bold red)"
vicmd_symbol = "[ï€](bold purple)"

