[colors]
background = '#161616'
foreground = '#f4f4f4'
cursor_bg = '#f4f4f4'
cursor_border = '#f4f4f4'
cursor_fg = '#161616'

ansi = [
    '#262626',
    '#fa4d56',
    '#42be65',
    '#ff832b',
    '#4589ff',
    '#ff7eb6',
    '#3ddbd9',
    '#c6c6c6',
]
brights = [
    '#393939',
    '#ff8389',
    '#42be65',
    '#fddc69',
    '#78a9ff',
    '#ffb3b8',
    '#82cfff',
    '#e0e0e0',
]

[colors.tab_bar]
background = "#0b0b0b"

[colors.tab_bar.active_tab]
bg_color = '#4589ff'
fg_color = '#f4f4f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "#0b0b0b"
fg_color = '#f4f4f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#0b0b0b'
fg_color = '#f4f4f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Carburator'
