[colors]
background = '#121619'
foreground = '#f2f4f8'
cursor_bg = '#f2f4f8'
cursor_border = '#f2f4f8'
cursor_fg = '#121619'

ansi = [
    '#21272a',
    '#fa4d56',
    '#42be65',
    '#ff832b',
    '#4589ff',
    '#ff7eb6',
    '#3ddbd9',
    '#c1c7cd',
]
brights = [
    '#343a3f',
    '#ff8389',
    '#42be65',
    '#fddc69',
    '#78a9ff',
    '#ffb3b8',
    '#82cfff',
    '#dde1E6',
]

[colors.tab_bar]
background = "#090b0c"

[colors.tab_bar.active_tab]
bg_color = '#4589ff'
fg_color = '#f2f4f8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "#090b0c"
fg_color = '#f2f4f8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#090b0c'
fg_color = '#f2f4f8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Carburator Cool'
